spring.application.name=Savemaker

# linking with database
spring.datasource.url=jdbc:postgresql://localhost:5432/savemaker
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# for testing purposes, always freshly create and then destroy the database
# TODO: remove when backend is complete
spring.jpa.hibernate.ddl-auto=create-drop

# always execute ./src/main/resources/data.sql
# TODO: remove when backend is complete
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always