INSERT INTO categories (id, name, is_used_for_income, preferred_spending_category_id) VALUES
                                                                                          (DEFAULT, 'Salary', true, NULL),
                                                                                          (DEFAULT, 'Scholarship', true, NULL),
                                                                                          (DEFAULT, 'Allowance', true, NULL),
                                                                                          (DEFAULT, 'Birthday money', true, NULL),
                                                                                          (DEFAULT, 'Freelance', true, NULL),
                                                                                          (DEFAULT, 'Other', true, NULL),
                                                                                          (DEFAULT, 'Groceries', false, 3),
                                                                                          (DEFAULT, 'Utility', false, 3),
                                                                                          (DEFAULT, 'Transport', false, 3),
                                                                                          (DEFAULT, 'Gaming', false, 1),
                                                                                          (DEFAULT, 'Social life', false, 1),
                                                                                          (DEFAULT, 'Other', false, 2);

INSERT INTO income_type_balances (id, category_id, balance, priority) VALUES
                                                                          (DEFAULT, 1, 2500.00, 1),
                                                                          (DEFAULT, 2, 1200.00, 2),
                                                                          (DEFAULT, 3, 800.00, 3),
                                                                          (DEFAULT, 4, 1500.00, 4),
                                                                          (DEFAULT, 5, 400.00, 5),
                                                                          (DEFAULT, 6, 1000.00, 6);

INSERT INTO main_balances (id, total_balance) VALUES
    (DEFAULT, 7400.00);

INSERT INTO income_type_balance_fk_table (main_balance_id, income_type_balance_id) VALUES
                                                                                       (1, 1),
                                                                                       (1, 2),
                                                                                       (1, 3),
                                                                                       (1, 4),
                                                                                       (1, 5),
                                                                                       (1, 6);

INSERT INTO transactions (id, date, notes, category_id) VALUES
                                                            (DEFAULT, '2025-03-01', 'Salary payment', 1),
                                                            (DEFAULT, '2025-03-05', 'Salary payment', 1),
                                                            (DEFAULT, '2025-03-10', 'Salary payment', 1),
                                                            (DEFAULT, '2025-03-15', 'Salary payment', 1),
                                                            (DEFAULT, '2025-03-20', 'Salary payment', 1),
                                                            (DEFAULT, '2025-03-12', 'Freelance project', 2),
                                                            (DEFAULT, '2025-03-15', 'Freelance project', 2),
                                                            (DEFAULT, '2025-03-18', 'Freelance project', 2),
                                                            (DEFAULT, '2025-03-22', 'Freelance project', 2),
                                                            (DEFAULT, '2025-03-25', 'Freelance project', 2),
                                                            (DEFAULT, '2025-03-25', 'Investment returns', 3),
                                                            (DEFAULT, '2025-03-28', 'Investment returns', 3),
                                                            (DEFAULT, '2025-04-05', 'Investment returns', 3),
                                                            (DEFAULT, '2025-04-10', 'Investment returns', 3),
                                                            (DEFAULT, '2025-04-15', 'Investment returns', 3),
                                                            (DEFAULT, '2025-04-01', 'Rental payment', 4),
                                                            (DEFAULT, '2025-04-05', 'Rental payment', 4),
                                                            (DEFAULT, '2025-04-10', 'Rental payment', 4),
                                                            (DEFAULT, '2025-04-15', 'Rental payment', 4),
                                                            (DEFAULT, '2025-04-20', 'Rental payment', 4),
                                                            (DEFAULT, '2025-04-25', 'Rental payment', 4),
                                                            (DEFAULT, '2025-05-01', 'Dividends received', 5),
                                                            (DEFAULT, '2025-05-05', 'Dividends received', 5),
                                                            (DEFAULT, '2025-05-10', 'Dividends received', 5),
                                                            (DEFAULT, '2025-05-15', 'Dividends received', 5),
                                                            (DEFAULT, '2025-02-01', '', 9),
                                                            (DEFAULT, '2025-02-05', '', 10),
                                                            (DEFAULT, '2025-02-10', '', 7),
                                                            (DEFAULT, '2025-02-12', '', 11),
                                                            (DEFAULT, '2025-02-15', '', 8),
                                                            (DEFAULT, '2025-02-20', '', 12),
                                                            (DEFAULT, '2025-02-25', '', 7),
                                                            (DEFAULT, '2025-03-01', '', 9),
                                                            (DEFAULT, '2025-03-03', '', 10),
                                                            (DEFAULT, '2025-03-08', '', 11),
                                                            (DEFAULT, '2025-03-11', '', 8),
                                                            (DEFAULT, '2025-03-14', '', 12),
                                                            (DEFAULT, '2025-03-18', '', 7),
                                                            (DEFAULT, '2025-03-21', '', 9),
                                                            (DEFAULT, '2025-03-23', '', 10),
                                                            (DEFAULT, '2025-03-26', '', 11),
                                                            (DEFAULT, '2025-03-29', '', 12),
                                                            (DEFAULT, '2025-04-02', '', 8),
                                                            (DEFAULT, '2025-04-04', '', 7),
                                                            (DEFAULT, '2025-04-07', '', 9),
                                                            (DEFAULT, '2025-04-09', '', 11),
                                                            (DEFAULT, '2025-04-13', '', 8),
                                                            (DEFAULT, '2025-04-16', '', 10),
                                                            (DEFAULT, '2025-04-20', '', 12),
                                                            (DEFAULT, '2025-04-22', '', 7),
                                                            (DEFAULT, '2025-04-25', '', 9);


INSERT INTO spending_details (id, category_id, amount) VALUES
                                                           (DEFAULT, 1, 2500.00),
                                                           (DEFAULT, 1, 2800.00),
                                                           (DEFAULT, 1, 3000.00),
                                                           (DEFAULT, 1, 2700.00),
                                                           (DEFAULT, 1, 2500.00),
                                                           (DEFAULT, 2, 1500.00),
                                                           (DEFAULT, 2, 1600.00),
                                                           (DEFAULT, 2, 1400.00),
                                                           (DEFAULT, 2, 1800.00),
                                                           (DEFAULT, 2, 1500.00),
                                                           (DEFAULT, 3, 1000.00),
                                                           (DEFAULT, 3, 1200.00),
                                                           (DEFAULT, 3, 900.00),
                                                           (DEFAULT, 3, 1000.00),
                                                           (DEFAULT, 3, 1100.00),
                                                           (DEFAULT, 4, 2200.00),
                                                           (DEFAULT, 4, 2500.00),
                                                           (DEFAULT, 4, 2300.00),
                                                           (DEFAULT, 4, 2200.00),
                                                           (DEFAULT, 4, 2400.00),
                                                           (DEFAULT, 4, 2500.00),
                                                           (DEFAULT, 5, 600.00),
                                                           (DEFAULT, 5, 450.00),
                                                           (DEFAULT, 5, 550.00),
                                                           (DEFAULT, 5, 500.00),
                                                           (DEFAULT, 1, 950.00),
                                                           (DEFAULT, 3, 550.00),
                                                           (DEFAULT, 4, 1200.00),
                                                           (DEFAULT, 2, 750.00),
                                                           (DEFAULT, 5, 400.00),
                                                           (DEFAULT, 6, 1700.00),
                                                           (DEFAULT, 1, 1000.00),
                                                           (DEFAULT, 2, 600.00),
                                                           (DEFAULT, 3, 500.00),
                                                           (DEFAULT, 4, 1350.00),
                                                           (DEFAULT, 5, 350.00),
                                                           (DEFAULT, 6, 1400.00),
                                                           (DEFAULT, 1, 1100.00),
                                                           (DEFAULT, 5, 300.00),
                                                           (DEFAULT, 2, 700.00),
                                                           (DEFAULT, 4, 1250.00),
                                                           (DEFAULT, 3, 450.00),
                                                           (DEFAULT, 1, 800.00),
                                                           (DEFAULT, 2, 650.00),
                                                           (DEFAULT, 6, 1600.00),
                                                           (DEFAULT, 3, 400.00),
                                                           (DEFAULT, 5, 500.00),
                                                           (DEFAULT, 6, 1500.00),
                                                           (DEFAULT, 4, 1300.00),
                                                           (DEFAULT, 1, 850.00),
                                                           (DEFAULT, 2, 800.00),
                                                           (DEFAULT, 5, 450.00),
                                                           (DEFAULT, 1, 950.00),
                                                           (DEFAULT, 3, 600.00),
                                                           (DEFAULT, 6, 1800.00),
                                                           (DEFAULT, 4, 1100.00),
                                                           (DEFAULT, 2, 750.00),
                                                           (DEFAULT, 6, 1700.00),
                                                           (DEFAULT, 3, 550.00),
                                                           (DEFAULT, 4, 1200.00),
                                                           (DEFAULT, 5, 400.00),
                                                           (DEFAULT, 1, 1000.00),
                                                           (DEFAULT, 2, 600.00);


INSERT INTO spending_details_transaction_table (transaction_id, spending_details_id) VALUES
                                                                                         (1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
                                                                                         (6, 6), (7, 7), (8, 8), (9, 9), (10, 10),
                                                                                         (11, 11), (12, 12), (13, 13), (14, 14), (15, 15),
                                                                                         (16, 16), (17, 17), (18, 18), (19, 19), (20, 20),
                                                                                         (21, 21), (22, 22), (23, 23), (24, 24), (25, 25),
                                                                                         (26, 26), (27, 27), (28, 28), (28, 29), (29, 30),
                                                                                         (30, 31), (31, 32), (31, 33), (32, 34), (33, 35),
                                                                                         (34, 36), (34, 37), (35, 38), (36, 39), (37, 40),
                                                                                         (37, 41), (38, 42), (39, 43), (40, 44), (40, 45),
                                                                                         (41, 46), (42, 47), (43, 48), (44, 49), (44, 50),
                                                                                         (45, 51), (46, 52), (47, 53), (48, 54), (49, 55),
                                                                                         (50, 56), (50, 57), (51, 58);
